// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4aQUkiyZlUpNbBdszkk1SAV8NrP1wYeg',
    appId: '1:24283980080:web:185e0017aef74ba45d28f5',
    messagingSenderId: '24283980080',
    projectId: 'eventmate-4ef43',
    authDomain: 'eventmate-4ef43.firebaseapp.com',
    storageBucket: 'eventmate-4ef43.firebasestorage.app',
    measurementId: 'G-WRZS9X5T4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx35yVkcsl3mw4rYpcouJ9yag7OyhvECg',
    appId: '1:24283980080:android:d558c8de6784f41c5d28f5',
    messagingSenderId: '24283980080',
    projectId: 'eventmate-4ef43',
    storageBucket: 'eventmate-4ef43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUCY7NNPG3xGvw-inaTi-rA1TXV1iXOgU',
    appId: '1:24283980080:ios:e47ffa5c1c3698475d28f5',
    messagingSenderId: '24283980080',
    projectId: 'eventmate-4ef43',
    storageBucket: 'eventmate-4ef43.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUCY7NNPG3xGvw-inaTi-rA1TXV1iXOgU',
    appId: '1:24283980080:ios:e47ffa5c1c3698475d28f5',
    messagingSenderId: '24283980080',
    projectId: 'eventmate-4ef43',
    storageBucket: 'eventmate-4ef43.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4aQUkiyZlUpNbBdszkk1SAV8NrP1wYeg',
    appId: '1:24283980080:web:327e53c3599b688b5d28f5',
    messagingSenderId: '24283980080',
    projectId: 'eventmate-4ef43',
    authDomain: 'eventmate-4ef43.firebaseapp.com',
    storageBucket: 'eventmate-4ef43.firebasestorage.app',
    measurementId: 'G-K1H8426RNP',
  );

}